### ISSUE TITLE
奖励函数bug情况

### ISSUE THREAD

**Issue by yuyan62** [mail-ecnu/VMAgent#11]
在运行train.py文件之后，生成的csv文件和tensorboard文件中的tot_reward和tot_length完全相等的情况。
一开始我用sched_env.py里面的单位奖励，然后得到两者相等是没问题的；但是我把单位奖励注释掉，奖励函数换成了代码中的另一个request['cpu']/self.cpu时，这时的结果应该是reward要小于length，但却没有按预想发生，仍然是两者相等；然后我就把奖励函数换成我自己设计的，发现实验结果里面两者还是一样相等。我在调用train.py文件里面的run函数时print每一次放置虚拟机的reward，发现不管是何种奖励函数，print处理的都是1。
下面是更神奇的事，我把sched_env.py里面的reward函数全部注释掉了，然后我运行train.py文件发现还是能运行，并且print出来的reward还是1。
请问作者这个是什么原因？以及如何解决？谢谢！

**Comment by chc199949** [comment]
你好，已经测试过注释掉单位奖励函数，换用request['cpu']/self.cpu奖励函数，train.py的run函数中得到的reward是正确按照request['cpu']/self.cpu进行计算的。
猜测你的问题是修改错了schedgym文件夹，注意VMAgent目录和vmagent目录下均有schedgym文件夹，若在VMAgent的命名空间中调用python vmagent/train.py，需要修改VMAgent目录下的schedgym中的reward函数；若在vmagent命名空间中直接调用python train.py，则对应修改vmagent下的schedgym中的reward函数。
